### ISSUE TITLE
Unable to create a container using LIBMR

### ISSUE THREAD

**Issue by somasundaram1702** [Vastlab/libMR#13]
Hi, I am trying to create an app in Google cloud platform. I give LIBMR in the requirement file, but it is asking for numpy. Though I have already given Numpy in the requriement, it stops the installation, and gives the below error,

Step #1: Collecting numpy==1.19.5
Step #1:   Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Step #1: Collecting libmr
Step #1:   Downloading libmr-0.1.9.zip (39 kB)
Step #1:     ERROR: Command errored out with exit status 1:
Step #1:      command: /env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-woar6lx9/libmr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-woar6lx9/libmr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a_kn5xwi
Step #1:          cwd: /tmp/pip-install-woar6lx9/libmr/
Step #1:     Complete output (5 lines):
Step #1:     Traceback (most recent call last):
Step #1:       File "<string>", line 1, in <module>
Step #1:       File "/tmp/pip-install-woar6lx9/libmr/setup.py", line 3, in <module>
Step #1:         import numpy
Step #1:     ModuleNotFoundError: No module named 'numpy'
Step #1:     ----------------------------------------
Step #1: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Step #1: WARNING: You are using pip version 20.2.2; however, version 21.0.1 is available.
Step #1: You should consider upgrading via the '/env/bin/python -m pip install --upgrade pip' command.
Step #1: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker@sha256:fb864d4f2bc3b4642a77cfb96adab6c449b2592ba6d41db388c171134b12b275" failed: step exited with non-zero status: 1

**Comment by yuliu213** [comment]
I have the same question, and  how did you solve it?

**Comment by sfeilaryan** [comment]
You are missing the Python.h file from the development files. You should lookup how to ensure it is there for your case. For instance on Linux, it would suffice to sudo apt-get install python3.X-dev. On Mac, brew can ensure its existence. I'm not sure what to do for your case. Good luck.

**Comment by eric8he** [comment]
Unfortunately it appears that in setup.py, Cython/NumPy are referenced before they are installed as dependencies. The workaround I found is to create a shell script that installs those dependencies, then libMR in a separate command.
