### ISSUE TITLE
run python example got AttributeError: 'libmr.MR' object has no attribute 'get_parms'

### ISSUE THREAD

**Issue by huangkeju** [Vastlab/libMR#14]
Hi, I installed libmr through pip install libmr. The version of libmr is 0.1.9. However, when I run python_example_plot.py in the examples folder, I got the following error:

Traceback (most recent call last):
  File "python_example_plot.py", line 22, in <module>
    print("scale shape sign translate score  " , mr.get_parms())
AttributeError: 'libmr.MR' object has no attribute 'get_parms'

Is it because I did not install the latest version?

**Comment by siebenkopf** [comment]
Thank you for reporting this issue. Indeed, this is a typo. The function is called `get_params`. Can you check if it works with this correction?

**Comment by huangkeju** [comment]
@siebenkopf Thanks as this error disappeared, but another error occurs:

Traceback (most recent call last):
  File "python_example_plot.py", line 23, in <module>
    print("scale lb up shape lb up  " , mr.get_confidene())
AttributeError: 'libmr.MR' object has no attribute 'get_confidene'

Even if I changed 'get_confidene' to 'get_confidence', this error still exists:

Traceback (most recent call last):
  File "python_example.py", line 15, in <module>
    print("scale lb up shape lb up  " , mr.get_confidence());
AttributeError: 'libmr.MR' object has no attribute 'get_confidence'

Maybe I'm not using the right version of  libmr?
